[package]
description = "library for building integration testing environments for cosmos-sdk chains in Rust"
edition     = "2021"
license     = "MIT OR Apache-2.0"
name        = "test-tube-ntrn"
repository  = "https://github.com/margined-protocol/test-tube"
version     = "0.1.7"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64       = { version = "0.21.5" }
cosmrs       = { version = "0.20.0", features = [ "cosmwasm", "rpc" ] }
cosmwasm-std = { version = "2.1.4" }
prost        = { version = "0.13.3", features = [ "prost-derive" ] }
serde        = { version = "1.0.144" }
serde_json   = { version = "1.0.85" }
thiserror    = { version = "1.0.34" }

[dev-dependencies]
cw1-whitelist = { version = "0.15.0" }
rayon         = { version = "1.5.3" }
